print("hello")
print("world")
print("This is a test script.")
print("End of script.")
print("Goodbye!")
print("This is the end of the test.")
print("Thank you for running the test.")
print("All done!")
print("Have a great day!")
print("Script execution complete.")
print("Final message: Test completed successfully.")
print("No errors encountered.")
print("Exiting the script now.")
print("version 1.")